image: conanio/gcc11

variables:
  BUILD_CONFIG: Release
  BUILD_DIR: build
  GIT_SUBMODULE_STRATEGY: recursive
  LLVM_SOURCE: "https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1"
  LLVM_SOURCE_NAME: "clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04"
  LLVM_SOURCE_EXT: "tar.xz"
  LLVM_DIR: ${CI_PROJECT_DIR}/llvm
  CONAN_CACHE_DIR: ${CI_PROJECT_DIR}/conan-cache
  VERILATOR_CACHE_DIR: ${CI_PROJECT_DIR}/verilator-cache
  VERILATOR_ROOT: ${CI_PROJECT_DIR}/verilator-cache
  APT_CACHE_DIR: apt-cache

stages:
  - build
  - test

cache:
  paths:
    - conan-cache
    - verilator-cache
    - apt-cache
    - llvm

before_script:
  - git config --global --add safe.directory '*'
  - echo "env_setup - preparing deb packages"
  - sudo rm -f /etc/apt/apt.conf.d/docker-clean
  - sudo mkdir -pv ${APT_CACHE_DIR}
  - sudo mkdir -p /var/cache/apt/archives
  - sudo mount --bind ${APT_CACHE_DIR} /var/cache/apt/archives/
  - sudo DEBIAN_FRONTEND=noninteractive apt update -q
  - sudo DEBIAN_FRONTEND=noninteractive apt upgrade -yq
  - sudo DEBIAN_FRONTEND=noninteractive apt install -yq libboost-filesystem-dev cmake make perl g++ libfl2 libfl-dev zlibc zlib1g zlib1g-dev ccache libgoogle-perftools-dev numactl perl-doc autoconf flex bison
  - mkdir -pv ${CI_PROJECT_DIR}/${CONAN_CACHE_DIR}
  - export CONAN_USER_HOME=${CONAN_CACHE_DIR}
  - echo "environment"
  - |
    conan user
    if ! [[ $(conan profile list) = *default* ]]
    then
      conan profile new default --detect
    fi
    conan profile update settings.compiler.libcxx=libstdc++11 default
  - echo "environment - preparing verilator"
  - |
    if [ ! -d ${VERILATOR_CACHE_DIR} ]
    then
      git clone https://github.com/verilator/verilator.git ${VERILATOR_CACHE_DIR}/
      cd ${VERILATOR_CACHE_DIR}/
      git checkout v4.202
      autoconf
      ./configure
      make -j$(nproc)
      cd ${CI_PROJECT_DIR}
    else
      echo "verilator already satisfied."
    fi
  - echo "environment - preparing llvm"
  - |
    if [ ! -d ${LLVM_DIR} ]
    then
      wget -nv --show-progress ${LLVM_SOURCE}/${LLVM_SOURCE_NAME}.${LLVM_SOURCE_EXT}
      tar xf ${LLVM_SOURCE_NAME}.${LLVM_SOURCE_EXT}
      mv ${LLVM_SOURCE_NAME} ${LLVM_DIR}
    else
      echo "llvm already satisfied."
    fi

build-job:
  stage: build
  script:
    - cd ${CI_PROJECT_DIR}
    - cmake -S ${CI_PROJECT_DIR} -B ${BUILD_DIR} -DVERILATOR_ROOT=${VERILATOR_CACHE_DIR} -DCMAKE_BUILD_TYPE=${BUILD_CONFIG} -DCMAKE_INSTALL_PREFIX=${BUILD_DIR}/installed -DLLVM_DIR=${LLVM_DIR}
    - cmake --build ${BUILD_DIR} --config ${BUILD_CONFIG} --parallel $(nproc)
    - cmake --install ${BUILD_DIR} --config ${BUILD_CONFIG}

  artifacts:
    paths:
      - ${BUILD_DIR}/CMakeFiles/CMakeOutput.log
      - ${BUILD_DIR}/CMakeFiles/CMakeError.log
    when: on_failure

test-job:
  stage: test
  script:
    - cd ${CI_PROJECT_DIR}
    - cmake -S ${CI_PROJECT_DIR} -B ${BUILD_DIR} -DVERBOSE=On -DTEST_BUILD=On -DVERILATOR_ROOT=${VERILATOR_CACHE_DIR} -DCMAKE_BUILD_TYPE=${BUILD_CONFIG} -DCMAKE_INSTALL_PREFIX=${BUILD_DIR}/installed -DLLVM_DIR=${LLVM_DIR}
    - cmake --build ${BUILD_DIR} --config ${BUILD_CONFIG} --parallel $(nproc)
    - cmake --build ${BUILD_DIR} --config ${BUILD_CONFIG} --parallel $(nproc) --target test
    - cat ${BUILD_DIR}/Testing/Temporary/LastTest.log
    - cat ${BUILD_DIR}/Testing/Temporary/CTestCostData.txt

  artifacts:
    paths:
      - ${BUILD_DIR}/CMakeFiles/CMakeOutput.log
      - ${BUILD_DIR}/CMakeFiles/CMakeError.log
      - ${BUILD_DIR}/Testing/*
    when: on_failure
